apiVersion: v1
kind: Pod
metadata:
  name: service-demo
  labels:   # these labels are used to registerthis pod with service 
    project: roboshop
    component: frontend
    environment: dev 
spec:
  containers: 
  - name: nginx
    image: nginx